version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: 'b1_words'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  bot:
    build:
      context: .
    env_file:
      - .env
    command: "alembic upgrade head"
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: