version: '3'
services:
  bot:
    build:
      context: .
    container_name: telegram_bot
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: 'b1_words'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'